version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test22Project
  gitServerName: githubacc
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
