version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test22Project
  gitServerName: githubacc
  gitUrl: https://github.com/rajkapoor-rajkapoor
  gitUsername: rajkapoor-rajkapoor
  gitBranch: main
services:
- serviceName: project.test22.integrations:date
  packages:
  - name: Test22Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.1.0.0.7
